apiVersion: v1
kind: Secret
metadata:
  name: lcet-secrets
type: Opaque
stringData:
  LCET_DB_URL: postgresql+asyncpg://lcet:CHANGE_ME@postgres:5432/lcet
  LCET_DB_URL_SYNC: postgresql://lcet:CHANGE_ME@postgres:5432/lcet
  postgres-user: lcet
  postgres-password: CHANGE_ME
  JWT_SECRET: CHANGE_ME_RANDOM_SECRET
